variables:
  PROJECT: $(System.TeamProject)
  ORG: $(System.TeamFoundationCollectionUri)

trigger:
  - master

pool:
  vmImage: 'windows-latest'
  
stages:
  - stage: ARM_Testing
    jobs:
    - job: ARMTTK
      steps:
        - task: RunARMTTKTests@1
          displayName: Run ARM TTK tests 
          name: TTKtests
          inputs:
            templatelocation: '$(System.DefaultWorkingDirectory)\templates'
            resultLocation: '$(System.DefaultWorkingDirectory)\results'

        - task: PublishTestResults@2
          displayName: Publish test restults
          name: PublishResults
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
          condition: always()

  - stage: Deploying_infrastructure
    jobs:
    - job: ARM_Template_deploying
      steps:       
        - task: AzurePowerShell@5 
          inputs:
            azureSubscription: 'Azure2'
            ScriptType: 'FilePath'
            ScriptPath: 'templates/azuredeploy.ps1'
            ScriptArguments: -Location ${env:LOCATION} -ResourceGroupName ${env:GROUP} -prefix ${env:prefix} -DatabasePassword $env:MAPPED_ENV_DB_PASS -TemplateFile templates\azuredeploy.json -TemplateParameterFile templates\azuredeploy.parameters.json
            azurePowerShellVersion: 'LatestVersion'
          env:
            MAPPED_ENV_DB_PASS: $(DatabasePassword)

        - bash: echo fucker $(output)
