variables:
  location: "eastus"
  prefix: "anoyher"

  PROJECT: $(System.TeamProject)
  ORG: $(System.TeamFoundationCollectionUri)
  LINK: $(Build.Repository.Uri)

trigger:
  - tester

pool:
  vmImage: "windows-latest"

stages:
  - stage: Deploying_infrastructure
    jobs:
      - job: ARM_Template_deploying
        steps:
          - task: AzurePowerShell@5
            name: PS_Deployment
            inputs:
              azureSubscription: "AzureNew"
              ScriptType: "FilePath"
              ScriptPath: "templates/azuredeploy.ps1"
              ScriptArguments: -Location ${env:location} -prefix ${env:prefix} -slackURL $env:MAPPED_SLACK_URL -userObjectID $env:MAPPED_USER_OBJECT_ID -templateUrlList ${env:templateUrlList}
              azurePowerShellVersion: "LatestVersion"
            env:
              MAPPED_SLACK_URL: $(slackURL)
              MAPPED_USER_OBJECT_ID: $(userObjectID)
              templateUrlList: $(Get_Template_URLs.templateUrlList)
