variables:
  location: "eastus"
  prefix: "legion"

  PROJECT: $(System.TeamProject)
  ORG: $(System.TeamFoundationCollectionUri)
  LINK: $(Build.Repository.Uri)

trigger:
  - tester

pool:
  vmImage: "windows-latest"

stages:
  - stage: Deploying_infrastructure
    jobs:
      - job: Get_Template_URLs
        steps:
          - task: AzurePowerShell@5
            name: Get_Template_URLs
            inputs:
              azureSubscription: "AzureNew"
              ScriptType: "FilePath"
              ScriptPath: "scripts/findTemplateURLs.ps1"
              ScriptArguments: -repoLink ${env:LINK} -branch $(Build.SourceBranchName) -dir ${env:TEMPLATE_DIR} -token $env:MAPPED_GITHUB_TOKEN
              azurePowerShellVersion: "LatestVersion"
            env:
              MAPPED_GITHUB_TOKEN: $(githubToken)
              TEMPLATE_DIR: "templates/artifacts/"

      - job: ARM_Template_deploying
        steps:
          - task: AzurePowerShell@5
            name: PS_Deployment
            inputs:
              azureSubscription: "AzureNew"
              ScriptType: "FilePath"
              ScriptPath: "templates/azuredeploy.ps1"
              ScriptArguments: -Location ${env:location} -prefix ${env:prefix} -slackURL $env:MAPPED_SLACK_URL -templateUrlList ${env:templateUrlList}
              azurePowerShellVersion: "LatestVersion"
            env:
              MAPPED_SLACK_URL: $(slackURL)
