variables:
  location: "eastus"
  groupName: "test"
  prefix: "testcase"

  PROJECT: $(System.TeamProject)
  ORG: $(System.TeamFoundationCollectionUri)

trigger:
  - master

pool:
  vmImage: "windows-latest"

stages:
  - stage: ARM_Testing
    jobs:
      - job: ARMTTK
        steps:
          - task: RunARMTTKTests@1
            displayName: Run ARM TTK tests
            name: TTKtests
            inputs:
              templatelocation: '$(System.DefaultWorkingDirectory)\templates'
              resultLocation: '$(System.DefaultWorkingDirectory)\results'

          - task: PublishTestResults@2
            displayName: Publish test restults
            name: PublishResults
            inputs:
              testResultsFormat: "NUnit"
              testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
  - stage: Deploying_infrastructure
    jobs:
      - job: ARM_Template_deploying
        steps:
          - task: AzurePowerShell@5
            name: PS_Deployment
            inputs:
              azureSubscription: "AzureNew"
              ScriptType: "FilePath"
              ScriptPath: "templates/azuredeploy.ps1"
              ScriptArguments: -Location ${env:location} -ResourceGroupName ${env:groupName} -prefix ${env:prefix} -slackURL $env:MAPPED_SLACK_URL
              azurePowerShellVersion: "LatestVersion"
            env:
              MAPPED_SLACK_URL: $(slackURL)
