variables:
  location: "eastus"
  prefix: "crfinal"
  subscription: "AzureNew"

  PROJECT: $(System.TeamProject)
  ORG: $(System.TeamFoundationCollectionUri)
  LINK: $(Build.Repository.Uri)

trigger:
  - main

pool:
  vmImage: "windows-latest"

stages:
  - stage: ARM_Testing
    jobs:
      - job: ARMTTK
        steps:
          - task: RunARMTTKTests@1
            displayName: Run ARM TTK tests
            name: TTKtests
            inputs:
              templatelocation: '$(System.DefaultWorkingDirectory)\templates'
              resultLocation: '$(System.DefaultWorkingDirectory)\results'
              allTemplatesMain: false
              ignoreExitCode: true

          - task: PublishTestResults@2
            displayName: Publish test restults
            name: PublishResults
            inputs:
              testResultsFormat: "NUnit"
              testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'

  - stage: Deploying_infrastructure
    jobs:
      - job: ARM_Template_deploying
        steps:
          - task: AzurePowerShell@5
            name: PS_Deployment
            inputs:
              azureSubscription: "$(subscription)"
              ScriptType: "FilePath"
              ScriptPath: "templates/azuredeploy.ps1"
              ScriptArguments: -Location ${env:location} -prefix ${env:prefix} -slackURL $env:MAPPED_SLACK_URL -userObjectID $env:MAPPED_USER_OBJECT_ID -templateUrlList ${env:templateUrlList}
              azurePowerShellVersion: "LatestVersion"
            env:
              MAPPED_SLACK_URL: $(slackURL)
              MAPPED_USER_OBJECT_ID: $(userObjectID)
              templateUrlList: $(Get_Template_URLs.templateUrlList)
